language: python

sudo: required

addons:
  apt:
    packages:
      - default-jdk

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true # Only required till travis-ci/travis-ci/issues/9815 is fixed

env:
  global:
    - TAGS="python"
    - GAUGE_TELEMETRY_ENABLED=false
    - GAUGE_PREFIX=/tmp
    - TERM=dumb

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script:
  - python build.py --test
  - curl -sSfL https://raw.githubusercontent.com/getgauge/infrastructure/master/nightly_scripts/install_latest_gauge_nightly.sh | bash
  - export PATH=/tmp/bin:$PATH
  - gauge -v
  - python build.py --dist
  - export GAUGE_PYTHON_VERSION=$(cd bin; ls gauge-python-*.zip | sed "s/^gauge-python-\([^;]*\).zip/\1/")
  - gauge uninstall python
  - gauge install python -f "bin/gauge-python-$GAUGE_PYTHON_VERSION.zip"
  - pip install "dist/getgauge-$GAUGE_PYTHON_VERSION.tar.gz"
  - gauge config gauge_repository_url  https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/
  - git clone git://github.com/getgauge/gauge-tests --depth 1 --recursive
  - cd gauge-tests
  - gauge install
  - gauge -v
  - ./gradlew clean pythonFT

