version: 1.0.{build}
environment:
    GAUGE_TELEMETRY_ENABLED: false
    GAUGE_PREFIX: C:\Program Files\Gauge\bin
install:
   - git submodule init
   - git submodule update
build_script:
- cmd: python --version
- cmd: pip --version

- cmd: pip install -r requirements.txt
- cmd: python build.py --test
- cmd: python build.py --install
- cmd: cd dist
- cmd: for %%f in (getgauge*) do pip install "%%f" --upgrade
- cmd: cd ..
- ps: >-
    git clone --depth=1 https://github.com/getgauge/gauge-tests

    cd gauge-tests

    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/getgauge/infrastructure/master/nightly_scripts/install_latest_gauge_nightly.ps1" -OutFile install_latest_gauge_nightly.ps1

    .\install_latest_gauge_nightly.ps1

    $env:Path="$env:ProgramFiles\Gauge\bin;" + [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

    Write-Host "PATH : $($env:PATH)"

    gauge config gauge_repository_url  https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/

    gauge install

    gauge -v
- .\gradlew.bat clean pythonFT
